### PR TITLE
also show badge for PRs

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by drnic** [comment]
Example URL:

http://cl.ly/image/0a1U0R1X1h0F/github-badge-pull.png

pull

**Comment by adg** [comment]
To submit code changed I'll need to ask you to sign the Google CLA, if you haven't already: https://cla.developers.google.com/

**Comment by drnic** [comment]
Done.

**Comment by adg** [comment]
Thanks!

**Pull request merged**
